import { adminUserId, learnerUserId, tenantAlphaId, tenantBetaId } from "./fixtures.js";
import {
  sampleAssignmentAlphaId,
  sampleCourseAlphaId,
  sampleCourseBetaId,
  sampleDraftCourseAlphaId,
  sampleLessonAlphaOneId,
  sampleLessonAlphaThreeId,
  sampleLessonAlphaTwoId,
  sampleLessonBetaOneId,
  sampleModuleAlphaId,
  sampleModuleBetaId,
  type AssignmentRecord,
  type CourseRecord,
  type ExerciseRecord,
  type GrammarPointRecord,
  type LessonBlockRecord,
  type LessonRecord,
  type ModuleRecord,
  type VocabularyItemRecord,
} from "./learning-domain.js";

const now = new Date("2026-04-27T09:00:00.000Z");

export const seedCourses: CourseRecord[] = [
  {
    id: sampleCourseAlphaId,
    tenantId: tenantAlphaId,
    language: "en",
    trackType: "business",
    targetLevel: "A1",
    title: "English A1 Workplace Starter",
    slug: "english-a1-workplace-starter",
    description: "A practical English starter course for workplace greetings and service basics.",
    status: "published",
    version: 1,
    createdBy: adminUserId,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: sampleDraftCourseAlphaId,
    tenantId: tenantAlphaId,
    language: "en",
    trackType: "general",
    targetLevel: "A2",
    title: "English A2 Travel Draft",
    slug: "english-a2-travel-draft",
    description: "Draft travel course kept invisible to learners.",
    status: "draft",
    version: 1,
    createdBy: adminUserId,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: sampleCourseBetaId,
    tenantId: tenantBetaId,
    language: "ja",
    trackType: "business",
    targetLevel: "N5",
    title: "Japanese N5 Retail Starter",
    slug: "japanese-n5-retail-starter",
    description: "A separate tenant course used to prove cross-tenant isolation.",
    status: "published",
    version: 1,
    createdBy: adminUserId,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedModules: ModuleRecord[] = [
  {
    id: sampleModuleAlphaId,
    tenantId: tenantAlphaId,
    courseId: sampleCourseAlphaId,
    title: "First workplace conversations",
    description: "Greetings, simple introductions, and polite service phrases.",
    orderIndex: 0,
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: sampleModuleBetaId,
    tenantId: tenantBetaId,
    courseId: sampleCourseBetaId,
    title: "Retail greetings",
    description: "Basic Japanese greetings for customer-facing work.",
    orderIndex: 0,
    status: "published",
    createdAt: now,
    updatedAt: now,
  },
];

export const seedLessons: LessonRecord[] = [
  {
    id: sampleLessonAlphaOneId,
    tenantId: tenantAlphaId,
    courseId: sampleCourseAlphaId,
    moduleId: sampleModuleAlphaId,
    title: "Greeting a guest",
    slug: "greeting-a-guest",
    description: "Practice short, polite greetings in a service context.",
    language: "en",
    targetLevel: "A1",
    estimatedMinutes: 8,
    objectives: ["Say hello politely", "Introduce your role", "Ask one simple question"],
    status: "published",
    version: 1,
    createdBy: adminUserId,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: sampleLessonAlphaTwoId,
    tenantId: tenantAlphaId,
    courseId: sampleCourseAlphaId,
    moduleId: sampleModuleAlphaId,
    title: "Asking for basic information",
    slug: "asking-for-basic-information",
    description: "Ask for a name, room number, and simple preference.",
    language: "en",
    targetLevel: "A1",
    estimatedMinutes: 10,
    objectives: ["Ask for a name", "Confirm a room number", "Use please and thank you"],
    status: "published",
    version: 1,
    createdBy: adminUserId,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: sampleLessonAlphaThreeId,
    tenantId: tenantAlphaId,
    courseId: sampleCourseAlphaId,
    moduleId: sampleModuleAlphaId,
    title: "Ending a short conversation",
    slug: "ending-a-short-conversation",
    description: "Close a conversation politely and offer help.",
    language: "en",
    targetLevel: "A1",
    estimatedMinutes: 9,
    objectives: ["Say goodbye politely", "Offer help", "Use a simple next step"],
    status: "published",
    version: 1,
    createdBy: adminUserId,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: sampleLessonBetaOneId,
    tenantId: tenantBetaId,
    courseId: sampleCourseBetaId,
    moduleId: sampleModuleBetaId,
    title: "Welcoming a customer",
    slug: "welcoming-a-customer",
    description: "Use simple Japanese greetings in a store.",
    language: "ja",
    targetLevel: "N5",
    estimatedMinutes: 8,
    objectives: ["Recognize いらっしゃいませ", "Say a simple welcome"],
    status: "published",
    version: 1,
    createdBy: adminUserId,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedLessonBlocks: LessonBlockRecord[] = seedLessons.flatMap((lesson, index) => [
  {
    id: crypto.randomUUID(),
    tenantId: lesson.tenantId,
    lessonId: lesson.id,
    type: "text",
    orderIndex: 0,
    content: {
      body:
        lesson.language === "en"
          ? "Use short, calm sentences and make eye contact when greeting a guest."
          : "Use a clear and polite greeting before asking what the customer needs.",
    },
    createdAt: new Date(now.getTime() + index * 1000),
    updatedAt: new Date(now.getTime() + index * 1000),
  },
  {
    id: crypto.randomUUID(),
    tenantId: lesson.tenantId,
    lessonId: lesson.id,
    type: "dialogue",
    orderIndex: 1,
    content: {
      lines:
        lesson.language === "en"
          ? [
              { speaker: "staff", text: "Good morning. Welcome to the hotel." },
              { speaker: "guest", text: "Good morning." },
            ]
          : [
              { speaker: "staff", text: "いらっしゃいませ。" },
              { speaker: "customer", text: "こんにちは。" },
            ],
    },
    createdAt: new Date(now.getTime() + index * 1000),
    updatedAt: new Date(now.getTime() + index * 1000),
  },
]);

export const seedVocabularyItems: VocabularyItemRecord[] = [
  {
    id: crypto.randomUUID(),
    tenantId: tenantAlphaId,
    language: "en",
    term: "welcome",
    meaning: "a polite greeting when someone arrives",
    partOfSpeech: "verb",
    level: "A1",
    tags: ["hospitality", "greeting"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    tenantId: tenantBetaId,
    language: "ja",
    term: "いらっしゃいませ",
    reading: "いらっしゃいませ",
    romanization: "irasshaimase",
    meaning: "welcome, used by staff to greet customers",
    partOfSpeech: "phrase",
    level: "N5",
    tags: ["retail", "greeting"],
    createdAt: now,
    updatedAt: now,
  },
];

export const seedGrammarPoints: GrammarPointRecord[] = [
  {
    id: crypto.randomUUID(),
    tenantId: tenantAlphaId,
    language: "en",
    title: "Polite simple present questions",
    pattern: "Can I + verb ...?",
    explanation: "Use Can I to offer help or ask permission in a simple polite way.",
    level: "A1",
    examples: [{ text: "Can I help you?" }],
    createdAt: now,
    updatedAt: now,
  },
];

export const seedExercises: ExerciseRecord[] = [
  {
    id: crypto.randomUUID(),
    tenantId: tenantAlphaId,
    lessonId: sampleLessonAlphaOneId,
    type: "multiple_choice",
    prompt: "Choose the most polite greeting.",
    content: {
      options: ["Hey you", "Good morning. Welcome to the hotel.", "What?"],
    },
    answerKey: {
      correctOptionIndex: 1,
    },
    explanation: "Good morning plus welcome is polite and service-appropriate.",
    points: 10,
    orderIndex: 0,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedAssignments: AssignmentRecord[] = [
  {
    id: sampleAssignmentAlphaId,
    tenantId: tenantAlphaId,
    courseId: sampleCourseAlphaId,
    assigneeType: "user",
    assigneeId: learnerUserId,
    assignedBy: adminUserId,
    dueDate: new Date("2026-05-15T00:00:00.000Z"),
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
];
